name: amr-tabtransformer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.1
  - scipy=1.13.0
  - scikit-learn=1.4.2
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - pytorch=2.2.2
  - pip
  - pip:
      - xgboost==2.0.3
      - catboost==1.2.5
      - optuna==3.6.1
      - shap==0.45.0
